name: Release 

on:
  push:
    branches: [ "master" ]
    
jobs:
  test:
    uses: JoepSchyns/tasker-reddit-wallpaper/.github/workflows/test.yml@master
  build:
    needs: test
    uses: JoepSchyns/tasker-reddit-wallpaper/.github/workflows/build.yml@master
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:

      contents: write
    steps:
      - name: Download release artifact

        uses: actions/download-artifact@v3

        with:

          name: release

      - uses: ncipollo/release-action@v1

        with:
          artifactErrorsFailBuild: true 
          allowUpdates: true
          tag: v0.0.0
          artifacts: release

