name: Release 

on:
  push:
    branches: [ "master" ]
    
jobs:
  test:
    uses: JoepSchyns/tasker-reddit-wallpaper/.github/workflows/test.yml@master
  build:
    needs: test
    uses: JoepSchyns/tasker-reddit-wallpaper/.github/workflows/build.yml@master
  deploy:
    needs: build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all artifacts
        uses: actions/download-artifact@v8

      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/dist/*.js"
          artifactErrorsFailBuild: true
          allowUpdates: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
     

