name: Release 

on:
  push:
    branches: [ "master" ]
    
jobs:
  test:
    uses: JoepSchyns/tasker-reddit-wallpaper/.github/workflows/test.yml@master
  build:
    needs: test
    uses: JoepSchyns/tasker-reddit-wallpaper/.github/workflows/build.yml@master
  deploy:
    runs-on: ubuntu-latest

    permissions:

      contents: write
    steps:

    - uses: actions/checkout@v3

    - uses: ncipollo/release-action@v1

      with:

        artifacts: "release"

