name: Release 

on:
  push:
    branches: [ "master" ]
    
jobs:
  test:
    uses: JoepSchyns/tasker-reddit-wallpaper/.github/workflows/test.yml@master
  build:
    needs: test
    uses: JoepSchyns/tasker-reddit-wallpaper/.github/workflows/build.yml@master
  deploy:
    needs: build
    runs-on: ubuntu-latest


    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
 
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
    
          artifacts: "release/*.js"
          artifactErrorsFailBuild: true 
          allowUpdates: true
          tag: v0.0.0
     

