name: Test

on:
  workflow_call:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
    - name: npm install and build
      run: |
        npm install
        npm run test
